# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4eed988540a0284c2a326d1663a87d671915c15bd61f8cabab437e303ba4e2256ef035c17158bf2918fc0a6ac437f243884bb7d8280d36bd22d492a2585e448

test:
  secret_key_base: c5fc8677a57267489aa610e34d20db1d588a2ee316b76d3bf18bcb3cddd9ff034bfe78e5020ad5f60406dd30ffddcfaaa70d1fa1a00452952980f3b0e15696da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
